---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes
  
  tasks:
    - name: clone/pull project repo
      git:
        repo: "{{ project_repo }}"
        dest: "{{ install_root }}/{{ project_name }}"
        accept_hostkey: yes

    - name: copy nginx config
      template: src=files/nginx.j2 dest=/etc/nginx/sites-enabled/{{ project_name }}.conf
      notify:
      - restart nginx

    - name: build the image
      command: docker build -t desafio:latest /srv/desafio

    - name: run desafio in a docker container
      command: docker run --name desafio -d -p 3000:3000 --link mongo:mongo --restart=always -d desafio:latest

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

# vim:ft=ansible:
