---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes
  
  tasks:
    - name: clone/pull project repo
      git:
        repo: "{{ project_repo }}"
        dest: "{{ install_root }}/{{ project_name }}"
        accept_hostkey: yes

    - name: copy nginx config
      template: src=files/nginx.j2 dest=/etc/nginx/sites-enabled/{{ project_name }}.conf
      notify:
      - restart nginx

    - name: build the image
        command: docker build -t desafio:latest .

    - name: run desafio in a docker container
      docker:
        name: desafio
        image:
        - "desafio:latest"
        state: reloaded
        pull: always
        ports:
        - "3000:3000"
        detatch: True
        use_tls: encrypt
        restart_policy: always
        links:
        - "mongodes:mongodb"

    handlers:
      - name: restart nginx
        service: name=nginx state=restarted

# vim:ft=ansible:
