---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes
  
  tasks:
    - name: clone/pull project repo
      git:
        repo: "{{ project_repo }}"
        dest: "{{ install_root }}/{{ project_name }}"
        accept_hostkey: yes
      notify:
      - restart gunicorn
      
    - name: install python packages
      pip:
        requirements: "{{ install_root }}/{{ project_name }}/requirements.txt"
        executable: pip3
      notify:

    - name: copy nginx config
      template: src=files/nginx.j2 dest=/etc/nginx/sites-enabled/{{ project_name }}.conf
      notify:
      - restart nginx

# vim:ft=ansible:
